### ISSUE TITLE
Invalid redirect_uri: Given URL is not allowed by the Application configuration

### ISSUE THREAD

**Issue by nitingohel** [philippec/PhFacebook#45]
Sorry to ask if there is minore mistake but i followed your suggestion step build framwork and add this in to my osx Window application. I also make sure that i added website at Developer.facebook page and there is i am setting the http://clopy.com/

and i setting as par your suggestion but i always get:

   "error": {
      "message": "Invalid redirect_uri: Given URL is not allowed by the Application configuration",
      "type": "OAuthException",
      "code": 191
   }
}

I do lots of google can you please tel me how to fix this issue. in code there is no any method for setting URl from code side there in framework only few method for get accesstoken and sendrequest.

**Comment by philippec** [comment]
I haven't used this framework in a while so it is possible that the method it is using is no longer supported. Feel free to poke around in the code and submit a PR if you get it working to your satisfaction.

**Comment by nitingohel** [comment]
Actually in too the documentation there said build Framework and use in to your project with release build and Debug build. i used that suggest code. 

    fb = [[PhFacebook alloc] initWithApplicationID: FB_APPLICATION_ID delegate: self];
    [fb getAccessTokenForPermissions: [NSArray arrayWithObjects: @"read_stream", @"export_stream", nil] cached: NO];
    [fb sendRequest:@"me/home"];
